import express from 'express'; import cors from 'cors'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import { roads, places, calculateRoutes, blockRoadForIncident } from './services/routeService.js'; import { predictRisk } from './services/riskService.js'; import { User, Incident } from './models/schemas.js';
const app=express(); app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'})); app.use(express.json({limit:'5mb'}));
const secret=()=>process.env.JWT_SECRET||'demo-secret-change-me'; const tokenFor=u=>jwt.sign({id:u._id||u.id,email:u.email,role:u.role},secret(),{expiresIn:'7d'});
const demoUsers=[{id:'demo-command',name:'Ananya Rao',email:'command@nershield.demo',password:'demo123',role:'COMMAND_OFFICER'},{id:'demo-driver',name:'Ravi Das',email:'driver@nershield.demo',password:'demo123',role:'FIELD_DRIVER'}];
app.get('/api/health',(req,res)=>res.json({status:'ok',database:mongooseReady?'connected':'demo-mode'})); let mongooseReady=false;
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password,role}=req.body; if(!mongooseReady){const u={id:Date.now(),name,email,role:role||'FIELD_DRIVER'}; return res.json({token:tokenFor(u),user:u});} const u=await User.create({name,email,password:await bcrypt.hash(password,10),role}); res.json({token:tokenFor(u),user:{name,email,role:u.role}});}catch(e){res.status(400).json({message:e.message});}});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body; let u=mongooseReady?await User.findOne({email}):demoUsers.find(x=>x.email===email); if(!u || (mongooseReady?!await bcrypt.compare(password,u.password):password!==u.password)) return res.status(401).json({message:'Invalid credentials'}); res.json({token:tokenFor(u),user:{name:u.name,email:u.email,role:u.role}});});
app.get('/api/auth/me',(req,res)=>{try{res.json(jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret()));}catch{res.status(401).json({message:'Unauthorized'});}});
app.post('/api/routes/calculate',async(req,res)=>{const {origin='Guwahati',destination='Silchar',priority='P1'}=req.body; const route=calculateRoutes(origin,destination); res.json({...route,origin,destination,priority,updatedAt:new Date()});});
app.get('/api/routes/active',(req,res)=>res.json({routes:calculateRoutes(),roads,places}));
app.post('/api/incidents',async(req,res)=>{const risk=await predictRisk(req.body.riskInput||{rainfall_24h:180,soil_moisture:86,slope_angle:32,elevation:400,road_condition:1}); const road=blockRoadForIncident(); const incident={...req.body,riskScore:risk.riskScore,createdAt:new Date()}; if(mongooseReady) await Incident.create(incident); const routes=calculateRoutes(req.body.origin||'Guwahati',req.body.destination||'Silchar'); req.app.io?.emit('incident:new',{incident,road}); req.app.io?.emit('risk:update',risk); req.app.io?.emit('route:updated',routes); req.app.io?.emit('cargo:update',{rerouted:true,eta:routes.bypass.eta}); res.status(201).json({incident,road,risk,routes});});
app.post('/api/risk/predict',async(req,res)=>res.json(await predictRisk(req.body)));
app.get('/api/demo/state',(req,res)=>res.json({roads,places,routes:calculateRoutes(),cargo:{id:'CVY-2048',type:'Vaccines',priority:'P1',temperature:'+4.1 C',location:'Guwahati',eta:165}}));
function setMongooseReady(value) { mongooseReady = value; }
export { app, setMongooseReady };
